name: final_exam
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0


  cached_network_image: ^3.4.1
  image_picker: ^1.1.0
  flutter_bloc: ^9.1.1
  infinite_scroll_pagination: ^5.1.0
  http: ^1.4.0
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  another_flushbar: ^1.12.30
  uuid: ^4.2.2
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
